
### valid request
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{"body": "This is an opinion I need to share with the world"}

### malformed request, wrong prop name
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{"test": "This is an opinion I need to share with the world"}

### malformed request, wrong type
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{"body": {"test":  123}}

### invalid request
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{"body": "This is an opinion I need to share with the world. That one might be a bit too long though. Better be exhaustive. Lorem ipsum dolor Integer posuere erat a ante venenatis dapibus posuere velit aliquet."}