### Create new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "test1234"
}

> {%
    client.test("is valid", function () {
        client.assert(response.status == 201, "status code should be 201")
    })
%}

### valid login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "test1234"
}

> {%
    client.test("is valid", function () {
        client.assert(response.status == 200, "status code should be 200")
    })
%}

### Update password
PUT http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIxIiwiZXhwIjoxNzE5ODcxNTIzLCJpYXQiOjE3MTk3ODUxMjN9.CODmElZRLdSxjLwec8cII9Sn3KZ91ntkUBOdmSq9DQc

{
  "email": "john@example.com",
  "password": "otherpass"
}

> {%
    client.test("is valid", function () {
        client.assert(response.status == 200, "status code should be 200")
    })
%}

### other valid login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "otherpass"
}

> {%
    client.test("is valid", function () {
        client.assert(response.status == 200, "status code should be 200")
    })
%}